### ISSUE TITLE
Developer integration workflow

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-lattice#1]
Allow a developer to run a service on the host (ie laptop) and have the services in lattice be able to hit the in IDE (or `java -jar`ed) app on the host.  The host service is visible to lattice via `192.168.11.1` which is the virtualbox gateway.  Not sure about other vagrant providers (vmware).

```
spring:
  cloud:
    lattice:
      - myService:
          host: 192.168.11.1 #could skip as this is the default
          port: 8765
```
